### ISSUE TITLE
searchDocuments: maxResults and skipResults incorrect

### ISSUE THREAD

**Issue by kju-digital-solutions** [atkjumedia/dcsync#1]
should be applied after QBE (Query by example) filtering

**Comment by WangYinXing** [comment]
https://github.com/atkjumedia/dcsync/commit/e1fc545d78c63f63a459fc1ef815b591f757da1d

Done.
Can you check it now?

**Comment by leowin** [comment]
now no results are returned, if maxResults is not set. Please use default values of 100 for maxResults and 0 for skipResults.

**Comment by WangYinXing** [comment]
sorry.
It's bug.
Will fix it.

**Comment by WangYinXing** [comment]
https://github.com/atkjumedia/dcsync/commit/0a3e38714f12f2d90790a6bf085a5361a3ae6520

Done.
